export let CompanyInfo = [
	{
		id: 1,
		'Mã CK': 'A32',
		'Sàn': 'UPCOM',
		'Ngày niêm yết': '2018-10-23',
		'Tên tiếng Việt': 'CTCP 32',
		'Giới thiệu': 'Công ty Cổ phần 32 (A32) có tiền thân là Xí nghiệp X32 - Bộ Quốc Phòng...',
		'Địa chỉ': 'Số 170 Quang Trung - P. 10 - Q. Gò Vấp - Tp. Hồ Chí Minh',
		'Website': '32jsc.com',
		'Ngành cấp 1': 'Hàng tiêu dùng',
		'Ngành cấp 2': 'Hàng tiêu dùng lâu bền và thời trang',
		'Ngành cấp 3': 'Hàng may mặc, phụ kiện và hàng hóa xa xỉ',
		'Ngành cấp 4': 'Giày dép',
		'Số lượng lưu hành (cổ phiếu)': 6800000,
		'Loại doanh nghiệp': 'Phi tài chính',
		'Vốn điều lệ (đồng)': 68000000000,
		'Sức mạnh giá': 66.22474747,
		'Trung bình khối lượng giao dịch 15 ngày (cổ phiếu)': 1840,
	},
	{
		id: 2,
		'Mã CK': 'AAA',
		'Sàn': 'HOSE',
		'Ngày niêm yết': '2016-11-25',
		'Tên tiếng Việt': 'CTCP Nhựa An Phát Xanh',
		'Giới thiệu': 'Công ty Cổ phần Nhựa An Phát Xanh (AAA) có tiền thân là Công ty TNHH Anh Hai Duy...',
		'Địa chỉ': 'Lô CN 11+CN 12 Cụm CN An Đồng - TT. Nam Sách - H. Nam Sách - T. Hải Dương',
		'Website': 'anphatbioplastics.com',
		'Ngành cấp 1': 'Nguyên vật liệu',
		'Ngành cấp 2': 'Nguyên vật liệu',
		'Ngành cấp 3': 'Hóa chất',
		'Ngành cấp 4': 'Sản phẩm từ nhựa',
		'Số lượng lưu hành (cổ phiếu)': 382274496,
		'Loại doanh nghiệp': 'Phi tài chính',
		'Vốn điều lệ (đồng)': 3822740000000,
		'Sức mạnh giá': 78.97727273,
		'Trung bình khối lượng giao dịch 15 ngày (cổ phiếu)': 2137460,
	},
	{
		id: 3,
		'Mã CK': 'AAH',
		'Sàn': 'UPCOM',
		'Ngày niêm yết': '2024-01-11',
		'Tên tiếng Việt': 'CTCP Hợp Nhất',
		'Giới thiệu': 'CTCP Hợp Nhất được thành lập ngày 11/07/2007. Công ty là một trong những đơn vị khai thác và thương mại than đứng đầu tỉnh Bắc Giang',
		'Địa chỉ': 'Tầng 2, Tòa nhà CT4, Vimeco 2, Phố Nguyễn Chánh, Phường Trung Hòa, Quận Cầu Giấy, Thành phố Hà Nội',
		'Website': 'thanhopnhat.com',
		'Ngành cấp 1': 'Năng lượng',
		'Ngành cấp 2': 'Năng lượng',
		'Ngành cấp 3': 'Dầu, khí đốt và nhiên liệu tiêu hao',
		'Ngành cấp 4': 'Khai thác than',
		'Số lượng lưu hành (cổ phiếu)': 117900000,
		'Loại doanh nghiệp': 'Phi tài chính',
		'Vốn điều lệ (đồng)': '1.179E+12',
		'Sức mạnh giá': '',
		'Trung bình khối lượng giao dịch 15 ngày (cổ phiếu)': '',
	},
	{
		id: 4,
		'Mã CK': 'AAM',
		'Sàn': 'HOSE',
		'Ngày niêm yết': '2009-09-24',
		'Tên tiếng Việt': 'CTCP Thủy sản MeKong',
		'Giới thiệu': 'Công ty Cổ Phần Thủy Sản Mê Kông (AAM) có tiền thân là Xí nghiệp Rau quả đông lạnh xuất khẩu Hậu Giang được thành lập vào năm 1979. Từ năm 2002, Công ty chính thức hoạt động theo mô hình công ty cổ phần. AAM là doanh nghiệp hoạt động trong lĩnh vực kinh doanh, chế biến xuất khẩu nông sản, thủy sản ở khu vực Đồng Bằng Sông Cửu Long - một khu vực có thế mạnh về nuôi trồng và kinh doanh nông thủy sản của cả nước hiện nay với các sản phẩm chính là cá tra fillet (có tổng công suất chế biến 9.000 tấn/năm), bạch tuộc (có tổng công suất chế biến 1.000 tấn/năm), mực cá đuối đông lạnh xuất khẩu và thủy sản khác xuất khẩu. Công ty hiện có 1 nhà máy với 3 phân xưởng chế biến. Hiện tại Thủy sản Mekong đứng ở vị trí thứ 15 trong số 168 Công ty hoạt động trong lĩnh vực chế biến thủy sản.',
		'Địa chỉ': 'Lô 24 KCN Trà Nóc - Q.Bình Thủy - Tp.Cần Thơ',
		'Website': 'mekongfish.vn',
		'Ngành cấp 1': 'Hàng tiêu dùng thiết yếu',
		'Ngành cấp 2': 'Thực phẩm, đồ uống và thuốc lá',
		'Ngành cấp 3': 'Sản phẩm thực phẩm',
		'Ngành cấp 4': 'Nuôi trồng và chế biến thủy sản',
		'Số lượng lưu hành (cổ phiếu)': 10451182,
		'Loại doanh nghiệp': 'Phi tài chính',
		'Vốn điều lệ (đồng)': '1.23464E+11',
		'Sức mạnh giá': 86.80555556,
		'Trung bình khối lượng giao dịch 15 ngày (cổ phiếu)': 5773.333333,
	},
	{
		id: 5,
		'Mã CK': 'AAS',
		'Sàn': 'UPCOM',
		'Ngày niêm yết': '2020-07-23',
		'Tên tiếng Việt': 'CTCP Chứng khoán SmartInvest',
		'Giới thiệu': 'Công ty Cổ phần Chứng khoán SmartInvest (AAS) có tiền thân là Công ty Cổ phần Chứng khoán Gia Anh được thành lập vào năm 2006. Công ty hoạt động trong lĩnh vực môi giới chứng khoán, tự doanh chứng khoán, bảo lãnh phát hành chứng khoán và tư vấn đầu tư chứng khoán. AAS trở thành công ty đại chúng từ năm 2019. Đối tác kinh doanh bao gồm Công ty CP Chứng khoán KIS Việt Nam, Công ty CP Chứng khoán Ngân hàng Đông Á, Công ty CP Chứng khoán An Bình, Công ty CP Chứng khoán Sài Gòn - Hà Nội, Công ty CP Chứng khoán Đại Dương, Công ty CP Chứng khoán Maritime Bank, Công ty CP Chứng khoán MB, Công ty CP Chứng khoán VN DIRECT, Công ty CP Chứng khoán SACOMBANK.',
		'Địa chỉ': 'Số 220, 222, 224 Phố Nguyễn Lương Bằng, Phường Quang Trung, Quận Đống Đa, Thành phố Hà Nội',
		'Website': 'sisi.com.vn',
		'Ngành cấp 1': 'Tài chính',
		'Ngành cấp 2': 'Dịch vụ tài chính',
		'Ngành cấp 3': 'Thị trường vốn',
		'Ngành cấp 4': 'Ngân hàng đầu tư và môi giới - chứng khoán',
		'Số lượng lưu hành (cổ phiếu)': 229999521,
		'Loại doanh nghiệp': 'Chứng khoán',
		'Vốn điều lệ (đồng)': '2.3E+12',
		'Sức mạnh giá': 83.96464646,
		'Trung bình khối lượng giao dịch 15 ngày (cổ phiếu)': 502593.3333,
	},
	{
		id: 6,
		'Mã CK': 'AAT',
		'Sàn': 'HOSE',
		'Ngày niêm yết': '2021-03-24',
		'Tên tiếng Việt': 'CTCP Tập Đoàn Tiên Sơn Thanh Hóa',
		'Giới thiệu': 'Công ty Cổ phần Tập đoàn Tiên Sơn Thanh Hóa (AAT), tiền thân là Công ty Tiên Sơn Thanh Hoá - TNHH được thành lập năm 1995 với số vốn điều lệ là 550 triệu đồng. Năm 2004, công ty chuyển đổi mô hình kinh doanh thành công ty cổ phần. Lĩnh vực kinh doanh chính của Công ty là May xuất khẩu; kinh doanh khách sạn; kinh doanh nông sản; cho thuê kho, xưởng sản xuất...',
		'Địa chỉ': 'Số 09 Khu Công Nghiệp Bắc Bỉm Sơn, Thị xã Bỉm Sơn, Tỉnh Thanh Hóa',
		'Website': 'tiensonaus.com',
		'Ngành cấp 1': 'Hàng tiêu dùng',
		'Ngành cấp 2': 'Hàng tiêu dùng lâu bền và thời trang',
		'Ngành cấp 3': 'Hàng may mặc, phụ kiện và hàng hóa xa xỉ',
		'Ngành cấp 4': 'Sản xuất sản phẩm may mặc công nghiệp',
		'Số lượng lưu hành (cổ phiếu)': 70819103,
		'Loại doanh nghiệp': 'Phi tài chính',
		'Vốn điều lệ (đồng)': '7.08191E+11',
		'Sức mạnh giá': 69.50757576,
		'Trung bình khối lượng giao dịch 15 ngày (cổ phiếu)': 68866.66667,
	},
];

